[package]
name = "settings"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json.workspace = true
serde.workspace = true
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
cipher = { path = "../cipher" }
