[package]
name = "token"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
serde_json.workspace = true
serde.workspace = true
bincode.workspace = true

proto = { path = "../proto" }
config = { path = "../config" }
errors = { path = "../errors" }
