[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
zilliqa = { path = "../zilliqa" }
serde = { version = "1.0.204", features = ["derive", "rc"] }
