[package]
name = "zilpay"
version = "0.1.0"
edition = "2021"

[dependencies]
zil_errors = { path = "../zil_errors" }
background = { path = "../background" }
crypto = { path = "../crypto" }
wallet = { path = "../wallet" }
settings = { path = "../settings" }
