[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
hex.workspace = true
sled.workspace = true
directories.workspace = true
zil_errors = { path = "../zil_errors" }
config = { path = "../config" }
